---
name: WWW-PhpfiCom-Create
version: 0.001
author:
  - 'Zoffix <zoffix@cpan.org>'
abstract: create new pastes on http://phpfi.com pastebin site
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 1.04
  Class::Data::Accessor: 0.04001
  HTTP::Request::Common: 1.28
  LWP::UserAgent: 2.036
  URI: 1.35
build_requires:
  Test::More: 0
provides:
  WWW::PhpfiCom::Create:
    file: lib/WWW/PhpfiCom/Create.pm
    version: 0.001
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
